stages:
  data_ingestion:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/data
    
  
  prepare_base_model:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage_02_prepare_base_model.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - BATCH_SIZE 
      - INCLUDE_TOP 
      - CLASSES 
      - WEIGHTS 
      - LEARNING_RATE
      - optimizer
      - loss
      - metrics
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage_03_training.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage_03_training.py
      - src/ChickenDiseaseClassification/components/prepare_callbacks.py
      - configs/config.yaml
      - artifacts/prepare_base_model
      - artifacts/data_ingestion/data
    params:
      - IMAGE_SIZE
      - BATCH_SIZE 
      - INCLUDE_TOP
      - EPOCHS
      - AUGMENTATION 
      - CLASSES 
      - WEIGHTS 
      - LEARNING_RATE
      - optimizer
      - loss
      - metrics
    outs:
      - artifacts/training/trained_model.h5

  model_evaluation:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage_04_model_evaluation.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage_04_model_evaluation.py
      - configs/config.yaml
      - artifacts/data_ingestion/data
      - artifacts/training/trained_model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false