artificats_root: artificats


data_ingestion:
  root_dir : artificats/data_ingestion
  source_url: https://github.com/umraliya-kevin/Chicken-Disease-Classification/raw/refs/heads/main/data.zip
  local_data_file: artificats/data_ingestion/data.zip
  unzip_dir: artificats/data_ingestion