artifacts_root: artifacts/

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/umraliya-kevin/Chicken-Disease-Classification/raw/refs/heads/main/data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
